### PR TITLE
Ch8 issue20

### LINKED ISSUE #20: What are some good practices in documenting high-level system architecture and processes of an AI solution?
**Section Outline**
This section consists of tips and techniques for creating and maintaining documentation of:
- high-level solution architecture 
- ML pipelines

**Definition of Done**
- [x] Completed `8-documentation-handover/documenting-architecture-processes.md`
- [x] Uploaded images to `assets` directory
- [x] Verified against [self-review checklist](https://docs.google.com/document/d/1jIFbca53uD8b2FsDrUR6Dlb7k20SlZQBt-jpJ_qV14Y/edit)
- [x] Page builds and displays correctly

### PR DESCRIPTION
**Pull request by snjannah**

### CODE REVIEW

**Comment by chuawjk** [comment]
Looks excellent. No comments from me (:

**Comment by ngkh2018** [comment]
1. The content is comprehensive and easy to understand. I have no further comments.

2. A side question, i.e. do we want to adopt C4 model for documentation across all future 100E  projects?

**Comment by najibninaba** [comment]
Looks good to me. Please proceed.

@ngkh2018 I believe various teams in 100E are already adopting C4 for their architecture diagrams. Should strongly recommend for the other teams as well.

**Comment by kevinosl** [comment]
Looks good to me too, no other comments.

**Comment by ryzalk** [comment]
Closing this pull request in view of the new merging workflow i.e. from contributing branches to `develop`.
CC @chuawjk

**Pull request closed without merging**
