### PR TITLE
How can we better evaluate Time-Series models?

### PR DESCRIPTION
**Pull request by andyozj**
re-opening issue #104

### CODE REVIEW

**Comment by ngkh2018** [comment]
@andyozj , I have reviewed this section and has no comments except for the minor feedback below:

In line 23, it would be good to put the acronyms, i.e. TP, FP, FN and TN, in brackets besides their long form, as the acronyms are used in the later part of the section.

**Comment by najibninaba** [comment]
As an aside, I like the styling of the graphs being drawn.

That said, I think the case study could be set up better. For example, it would be good to state early and not near the end of the case study write-up that Company A is planning to use the model for machinery fault detection.

Agree with Kim Hock's comment regarding the acronyms, and I wonder if it's better to show a confusion matrix table.

**Comment by kevinosl** [comment]
@andyozj Similar to the other PR, I'm unable to leave inline code comments, so here's the consolidated list.

- Suggest renaming this `How can we better evaluate Time-Series classification models?`. This is to avoid confusion with the more traditional notion of time series forecasting, which are usually regression-type models.

- After this line in the intro `This guide assumes that you have a fair understanding of the typical classification evaluation metrics.`, suggest to insert an additional point `This [article ](url)provides a high-level discussion of the topic.`. And provide a link to Yuyang's article on classification metrics.

- After this line `For regression problems, we can use Mean Squared Error(MSE) or Root Mean Square Error(RMSE) to evaluate.`, can add this `This article focuses on time-series classification problems, where the outcome to be predicted/forecasted is categorical.`. This gives the readers the context of what we will be focusing on.

- I find that this line `For a time-series classification project, the typical approach is to view every timepoints individually. We will then evaluate the model by looking at its F1 Score or precision and recall (similar to a normal classification problem)` may be slightly confusing to some readers. Because on one hand, we're saying individual timepoint evaluation is typical, but later, we are also saying that it is not proper. So I suggest rephrasing it as `For a time-series classification project, a simple approach is to view every timepoints individually, and evaluate the model by looking at its F1 Score or precision and recall (similar to a non-time-series classification problem)`.

- After this line `However, this can be too sensitive for a time-series dataset.`, suggest to add this `It is susceptible to noise. It also ignores the autocorrelated nature of time-series data, which tends to result in sequences of points falling into the same class, rather than one-off occurrences.`. This adds the technical reasoning for why we look for alternative versions of classification metrics for time series problems.

- General comment: may want to standardise whether we want to use caps (Time-Series) or non-caps (time-series) throughout the article.

**Comment by andyozj** [comment]
Thanks all for the suggestions, I've made the appropriate amendments to reflect these suggestions.

@najibninaba I've actually included the various TPs/FPs etc in the table, but do you think I've should have listed these metrics in their matrix format?

**Pull request merged**
