### PR TITLE
Ch3 issue19

### PR DESCRIPTION
**Pull request by snjannah**

### CODE REVIEW

**Comment by chuawjk** [comment]
Hi @snjannah, I think this is excellent. Wish I had something like this when I was starting out!

I have no comments for now.

Don't worry about the failed `proselint`, I'll figure out a way to manage it.

**Comment by ngkh2018** [comment]
1. Would it be useful to include (under the ‘References’ section) links to some common open-source frameworks on project templates?

**Comment by snjannah** [comment]
@ngkh2018 I added a link to AISG's cookie-cutter template. Besides this, I've only used Kedro myself. Maybe other engineers have their own favourites.

**Comment by kevinosl** [comment]
No other comments from me here.

**Comment by ryzalk** [comment]
Closing this pull request in view of the new merging workflow i.e. from contributing branches to `develop`.
CC @chuawjk

**Pull request closed without merging**
