### PR TITLE
Ch5 issue119

### PR DESCRIPTION
**Pull request by joshxinjie**
Repeatable data splits

### CODE REVIEW

**Comment by ngkh2018** [comment]
Below are 2 minor comments for this section:

1. Would be good to explain what the following acronyms stand for:
    - NER
    - NLP
    - MUC

2. For the explanation of COR metric, I suggest to express more explicitly as ‘The output of a system and the golden annotation are the same’

**Review by najibninaba — APPROVED** [review]
>> The article assumes that the reader has some (but not necessarily extensive) knowledge of an AI project life cycle and typical activities that occur in each stage.

Can we link to show what we meant by AI project life cycle (perhaps something we have standardised on)?

Overall, this is a good and concise write-up.

**Comment by chuawjk** [comment]
@najibninaba Sorry for the confusion arising from having to reopen a PR for this issue. This PR pertains to the article "How do we make data splits repeatable?" (linked below). Could I trouble you for comments on this, please?
https://oss.gitlab.aisingapore.net/aisg-handbook/ai-practitioner-handbook/book/5-data-mgmt-exp-proc/data-splits-repeatable.html

**Comment by kevinosl** [comment]
Thanks for the very beneficial article Xin Jie. Below are my suggestions:

- As part of the context at the top of the article, I think it will be good to also mention that we assume the reader is aware of individual token-level classification schemes for NER, eg. BIO. Can provide a link to any standard NER resource that explains this.

- Suggest expanding on this part slightly, to help readers who are newer to NER understand the objective better:
`.. , it may be more beneficial to aggregate the individual tokens into full named-entities, and evaluate NER models at a full named-entity level instead. This also makes the evaluation more relatable for the client.`

- Suggest providing the full name of MUC, as well as a link to the ACL Anthology page (link found in the blog).
Will it be better to introduce MUC first as the building blocks, before SemEval? When introducing SemEval, we can then explain it in terms of something like `It provides 4 different options for measuring the overall performance. They differ in terms of what is considered to be correct, incorrect, partial, missed and spurious predictions.`

- Btw, I couldn’t load the SemEval diagram, do check.

- For the example at the end, it may be good to write a short 1-2 lines on the differences in results based on the 4 measures, and what is the implication. Eg. we might advise the client to evaluate the model based on Type, if for their use case it is more critical that the class of the entity is predicted correctly, rather than having the boundary of the phrases match exactly.

- Lastly, will it be better to name the article `What are some of the common metrics in Named Entity Recognition`?

**Pull request merged**
