### PR TITLE
Ch5 issue30

### LINKED ISSUE #30: Which data storage options are suitable for my project?
**Section Outline**
- Types of common business problems 
- Data storage recommendation for said business problems

**Definition of Done**
- [ ] Completed `5-data-mgmt-exp-proc/data-mgmt.md`
- [ ] Verified against [self-review checklist](../blob/main/REVIEWING.md)
- [ ] Page builds and displays correctly

### PR DESCRIPTION
**Pull request by Syakyr**

### CODE REVIEW

**Comment by chuawjk** [comment]
Thanks @Syakyr, I think this is an excellent overview. I learnt a lot from your article, and I believe there are many other engineers who will benefit.

I don't have much prior background in data management solutions, so I can only provide very brief inputs on this.

When I saw "data management" in the title, I had initially (and mistakenly) understood that as something more end-to-end, encompassing, storage, data processing and versioning. As such, could I suggest that you provide a brief definition of what is meant by "data management" in the introduction, so that readers could be aligned on what would subsequently be discussed in the article?

**Comment by najibninaba** [comment]
I think the answer to this question can be too exhaustive and potentially go over our constraints. I believe what will be more effective to provide some guiding questions on selecting the right data management solution for the project requirements.

There is also a mix of data formats (CSVs, Excel, JSON, etc) vs. data stores (Object Stores, SQL, NoSQL, etc) concepts which can be confusing and does not address the question.

I recommend that asking the guiding questions that hopefully identify potential design decisions will be the better approach. And for any actual description of a technical concept such as data formats, data models, platforms, to point to external, more authoritative sources.

Do look at https://docs.microsoft.com/en-sg/azure/architecture/guide/technology-choices/data-store-overview and https://docs.microsoft.com/en-sg/azure/architecture/guide/technology-choices/data-store-considerations for something along these lines.

**Comment by Syakyr** [comment]
I have changed the scope to something that might be aligned to what we have discussed during the last sprint review.

**Comment by kevinosl** [comment]
Looks good guys. My only comment is similar to that for the basic workflow article. If there is a framework we are referencing, would be good to caption it and place the link in the References.
Also, would it be good to color code the nodes parked under Basic and Enhanced differently, in both articles? That might aid viewers to orientate themselves more easily to the workflow diagram.

**Comment by kevinosl** [comment]
Thanks Syakyr, this looks good and relates to the questions that engineers may have. A few comments:

- If I may suggest, an additional consideration is **Requirements and Competency of Project Sponsor**. Besides the competency level of our team, we may also need to factor in the client's deployment requirements and/or their readiness level. In some cases, they might request something more sustainable than csv. In other cases, their team may not be ready to handle databases and are only comfortable with csv.

- the AI readiness index pertains more to the client than our team. So I would suggest i) renaming the 1st point Competency of AISG Team, ii) moving the readiness index discussion to the new point about client's competency level.

- as the handbook is geared towards our engineers (as opposed to an organisation's in-house data scientists or engineers), setting up a data lake or warehouse is generally not a viable option, as we don't typically get involved in such a scope. Perhaps we can strip this down a little by changing mentions of data lake/warehouse to just relational database or NoSQL schema?

- would another consideration be **Format and Type of Data**? For NLP and CV projects, the storage solutions required may differ from a purely tabular data project.

**Comment by Syakyr** [comment]
Ah, I was under the impression that the handbook's meant for external organisations to have a look at to determine their suitability in engaging with us (AKA what questions we might ask them so that our work would be easier to match what their needs are). I'll make the changes accordingly.

**Comment by Syakyr** [comment]
> * If I may suggest, an additional consideration is **Requirements and Competency of Project Sponsor**. Besides the competency level of our team, we may also need to factor in the client's deployment requirements and/or their readiness level. In some cases, they might request something more sustainable than csv. In other cases, their team may not be ready to handle databases and are only comfortable with csv.
> * the AI readiness index pertains more to the client than our team. So I would suggest i) renaming the 1st point Competency of AISG Team, ii) moving the readiness index discussion to the new point about client's competency level.

With regards to these 2 points, I've reworded the subsection such that it focuses more towards the competencies of the project sponsor. I don't think the competency of the AISG team would be part of the consideration since we would expect the team to learn to adapt in accordance to the project sponsor's requirement. Any scope that is to be defined should already be done in Chapter 2, especially for something that is to be provisioned within the 7 months time frame.

> * as the handbook is geared towards our engineers (as opposed to an organisation's in-house data scientists or engineers), setting up a data lake or warehouse is generally not a viable option, as we don't typically get involved in such a scope. Perhaps we can strip this down a little by changing mentions of data lake/warehouse to just relational database or NoSQL schema?

Ah, that paragraph is a means to give an example on how simple or complex the set up for data storage options can be. I would say that it is to bring to light the existence of data lakes and warehouses; a sort-of move from "not knowing what you don't know", to a state of "knowing what you don't know". As the reader reads ahead, there would be references on what kind of data stores they can consider, especially towards the section from Microsoft that @najibninaba recommended. I suppose it could be worded a little better to give reference to it earlier, but I find it not suitable to bunch links up together in a single subsection.

> * would another consideration be **Format and Type of Data**? For NLP and CV projects, the storage solutions required may differ from a purely tabular data project.

I would say that is part of the Data Management subsection, also the storage solution reference is given in the Reliability and Consistency subsection. But I suppose it would need to be worded better there as well.

**Comment by ryzalk** [comment]
Closing this pull request in view of the new merging workflow i.e. from contributing branches to `develop`.
CC @chuawjk

**Pull request closed without merging**
