### PR TITLE
What are some of the factors/questions that an AI Engineer should consider during literature review?

### PR DESCRIPTION
**Pull request by andyozj**
reopen PR for issue #101

### CODE REVIEW

**Comment by ngkh2018** [comment]
@andyozj, here's my review comments:

1. In project, wrt using third party codes/libraries, the project team usually goes for permissive license (e.g. BSD, MIT) or weak copyleft license (e.g. GNU LGPL) and avoids copyleft license (e.g. GPL) and commercial IP software. It would be good to include this consideration, if it is also applicable to the papers (and their code repositories) studied during literature review.

2. in line 22, ‘be’ is missing… ‘and development time may not sufficient to build pipelines from scratch’ —> ‘and development time may not be sufficient to build pipelines from scratch’

**Review by najibninaba — APPROVED** [review]
Kim Hock gave good feedback regarding the copyrights, and for research papers, they also have their considerations for copyrights and agreements.  It would be good to mention them.

**Comment by kevinosl** [comment]
@andyozj  I'm unable to comment inline in Files Changed (could it be because the PR was renamed before?), so I'm consolidating all my comments inside the Conversations tab here.

**Business Needs**
- Could you give a quick example to help readers understand what a 'similar domain' means? This is because some readers may have different interpretations. Eg. do you define 'domain' to refer broadly to 'industry', such that if the engineer is working on a solution for a finance client, it is recommended that they research on literature that discusses an application in the finance industry?

- The medical example is good! Suggest to add another example along with it: mode of deployment. Eg. `If the use case calls for edge deployment in mobile devices, then this would further guide the choice of literature towards those that cater to smaller and faster models.`
 
**Development Time**
- Suggest to add a line linking this section to the following sections on code existence/pretrained model. Eg. `The following sections are specific examples of strategies that can aid in shortening development time.`

**Code Existence & Readability**
- Suggest to add a point `Some repositories/implementations may also be more complete than others, eg. those that include an evaluation function, or have class weights as part of its tunable hyperparameters.`

**Open-Sourcing of a pre-trained model**
- Suggest to add a point `If the pre-trained model was trained on a dataset from a similar domain to your use case, that is a plus point. Eg. FinBERT is a pre-trained NLP model to analyze sentiment of financial text, which may be more directly applicable than bert-base if your use case involves analyzing financial statements.`

**Key takeaways from the literature**
- May not be nice to say that results are inflated (though we know it). Some of our readers might also write papers! :) Another way to say it is that they "may involve a degree of cherry-picking".

**Comment by andyozj** [comment]
@najibninaba @ngkh2018 Thanks for the suggestions, these copyrights/licenses are indeed important for an AI project.

@kevinosl I agree that the phrase "similar domain" might be confusing/easily interpreted by others. I will add an example to further explain this phrase. 

Thank you all for the suggestions,  I will include these considerations into my article.

**Pull request merged**
